---
collections: 
  - name: community.cip
    version: 1.0.1
    source: https://galaxy.ansible.com/

  - name: community.general
    source: https://galaxy.ansible.com/
    version: 11.1.2

  - name: test.new_collection
    version: 1.0.0
    source: https://aap.lab.example.com/api/galaxy/

  - name: amazon.aws
    source: https://console.redhat.com/api/automation-hub/content/published/
    version: 10.1.1
