- name: Example of nested loop using with_nested
  hosts: servera.lab.example.com
  gather_facts: false

  vars:
    environments:
      - dev
      - test
      - prod

    applications:
      - frontend
      - backend
      - database

  tasks:
    - name: Show each environment and application combination
      debug:
        msg: "Deploying {{ item.1 }} in {{ item.0 }} environment"
      with_nested:
        - "{{ environments }}"
        - "{{ applications }}"

