---
- name: Retry task until file exists
  hosts: servera.lab.example.com
  gather_facts: false

  tasks:
    - name: Wait for file to be created
      ansible.builtin.stat:
        path: /tmp/myflag.txt
      register: file_check
      retries: 5
      delay: 3
      until: file_check.stat.exists

    - name: Print success message
      debug:
        msg: "The file /tmp/myflag.txt was found!"
      when: file_check.stat.exists

