---
- name: Working with special purpose modules
  hosts: serverc.lab.example.com
  become: true
  tasks:

  # Using Command module to install a package

    - name: Installing httpd package using a command module
      ansible.builtin.command:
        cmd: sudo dnf install httpd -y

  # Using Special Purpose Modules to install a package

    - name: Installing httpd package using specialized module
      ansible.builtin.dnf:
        name: httpd
        state: present
